vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
        cakes:
            uri_prefix: /img/cakes
            upload_destination: '%kernel.project_dir%/www/img/cakes'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer