<?php

namespace ContainerX4KwoVS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_EkiheOlService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.EkiheOl' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.EkiheOl'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\Admin\\AdminCakesController::show' => ['privates', '.service_locator.o_YhXT_', 'get_ServiceLocator_OYhXTService', true],
            'App\\Controller\\Admin\\AdminCakesController::spotlightToggle' => ['privates', '.service_locator.o_YhXT_', 'get_ServiceLocator_OYhXTService', true],
            'App\\Controller\\Admin\\AdminCakesController::update' => ['privates', '.service_locator.o_YhXT_', 'get_ServiceLocator_OYhXTService', true],
            'App\\Controller\\Admin\\SecurityController::login' => ['privates', '.service_locator.rSTd.nA', 'get_ServiceLocator_RSTd_NAService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Controller\\Admin\\AdminCakesController:show' => ['privates', '.service_locator.o_YhXT_', 'get_ServiceLocator_OYhXTService', true],
            'App\\Controller\\Admin\\AdminCakesController:spotlightToggle' => ['privates', '.service_locator.o_YhXT_', 'get_ServiceLocator_OYhXTService', true],
            'App\\Controller\\Admin\\AdminCakesController:update' => ['privates', '.service_locator.o_YhXT_', 'get_ServiceLocator_OYhXTService', true],
            'App\\Controller\\Admin\\SecurityController:login' => ['privates', '.service_locator.rSTd.nA', 'get_ServiceLocator_RSTd_NAService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
        ], [
            'App\\Controller\\Admin\\AdminCakesController::show' => '?',
            'App\\Controller\\Admin\\AdminCakesController::spotlightToggle' => '?',
            'App\\Controller\\Admin\\AdminCakesController::update' => '?',
            'App\\Controller\\Admin\\SecurityController::login' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\Admin\\AdminCakesController:show' => '?',
            'App\\Controller\\Admin\\AdminCakesController:spotlightToggle' => '?',
            'App\\Controller\\Admin\\AdminCakesController:update' => '?',
            'App\\Controller\\Admin\\SecurityController:login' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
