<?php

namespace ContainerX4KwoVS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_OYhXTService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.o_YhXT_' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.o_YhXT_'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'cake' => ['privates', '.errored..service_locator.o_YhXT_.App\\Entity\\Cake', NULL, 'Cannot autowire service ".service_locator.o_YhXT_": it needs an instance of "App\\Entity\\Cake" but this type has been excluded in "config/services.yaml".'],
        ], [
            'cake' => 'App\\Entity\\Cake',
        ]);
    }
}
