<?php

namespace ContainerX4KwoVS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCakeRepositoryService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Repository\CakeRepository' shared autowired service.
     *
     * @return \App\Repository\CakeRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Repository'.\DIRECTORY_SEPARATOR.'CakeRepository.php';

        $a = ($container->services['knp_paginator'] ?? $container->load('getKnpPaginatorService'));

        if (isset($container->privates['App\\Repository\\CakeRepository'])) {
            return $container->privates['App\\Repository\\CakeRepository'];
        }

        return $container->privates['App\\Repository\\CakeRepository'] = new \App\Repository\CakeRepository(($container->services['doctrine'] ?? $container->getDoctrineService()), $a);
    }
}
