<?php

namespace ContainerX4KwoVS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCakeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.o_YhXT_.App\Entity\Cake' shared service.
     *
     * @return \App\Entity\Cake
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.o_YhXT_": it needs an instance of "App\\Entity\\Cake" but this type has been excluded in "config/services.yaml".');
    }
}
