<?php

namespace ContainerX4KwoVS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCurrentPasswordValidatorService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Validator\CurrentPasswordValidator' shared autowired service.
     *
     * @return \App\Validator\CurrentPasswordValidator
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'validator'.\DIRECTORY_SEPARATOR.'ConstraintValidatorInterface.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'validator'.\DIRECTORY_SEPARATOR.'ConstraintValidator.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Validator'.\DIRECTORY_SEPARATOR.'CurrentPasswordValidator.php';

        $a = ($container->privates['security.helper'] ?? $container->load('getSecurity_HelperService'));

        if (isset($container->privates['App\\Validator\\CurrentPasswordValidator'])) {
            return $container->privates['App\\Validator\\CurrentPasswordValidator'];
        }

        return $container->privates['App\\Validator\\CurrentPasswordValidator'] = new \App\Validator\CurrentPasswordValidator(($container->privates['security.user_password_hasher'] ?? $container->load('getSecurity_UserPasswordHasherService')), $a);
    }
}
