<?php

namespace ContainerX4KwoVS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLocationRepositoryService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Repository\LocationRepository' shared autowired service.
     *
     * @return \App\Repository\LocationRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Repository'.\DIRECTORY_SEPARATOR.'LocationRepository.php';

        return $container->privates['App\\Repository\\LocationRepository'] = new \App\Repository\LocationRepository(($container->services['doctrine'] ?? $container->getDoctrineService()));
    }
}
