<?php

namespace ContainerX4KwoVS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getVisitRepositoryService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Repository\VisitRepository' shared autowired service.
     *
     * @return \App\Repository\VisitRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Repository'.\DIRECTORY_SEPARATOR.'VisitRepository.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Services'.\DIRECTORY_SEPARATOR.'DateTimeHelper.php';

        $a = ($container->services['knp_paginator'] ?? $container->load('getKnpPaginatorService'));

        if (isset($container->privates['App\\Repository\\VisitRepository'])) {
            return $container->privates['App\\Repository\\VisitRepository'];
        }

        return $container->privates['App\\Repository\\VisitRepository'] = new \App\Repository\VisitRepository(($container->services['doctrine'] ?? $container->getDoctrineService()), $a, new \App\Services\DateTimeHelper());
    }
}
