<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerX3A4xm2\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerX3A4xm2/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerX3A4xm2.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerX3A4xm2\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerX3A4xm2\App_KernelProdContainer([
    'container.build_hash' => 'X3A4xm2',
    'container.build_id' => '1b96fd9d',
    'container.build_time' => 1674228227,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerX3A4xm2');
