<?php

namespace ContainerX3A4xm2;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAuthenticationSubscriberService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\EventSubscriber\AuthenticationSubscriber' shared autowired service.
     *
     * @return \App\EventSubscriber\AuthenticationSubscriber
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['security.helper'] ?? $container->load('getSecurity_HelperService'));

        if (isset($container->privates['App\\EventSubscriber\\AuthenticationSubscriber'])) {
            return $container->privates['App\\EventSubscriber\\AuthenticationSubscriber'];
        }

        return $container->privates['App\\EventSubscriber\\AuthenticationSubscriber'] = new \App\EventSubscriber\AuthenticationSubscriber(($container->services['request_stack'] ??= new \Symfony\Component\HttpFoundation\RequestStack()), $a);
    }
}
