<?php

namespace ContainerX3A4xm2;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAdminOrderControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\Admin\AdminOrderController' shared autowired service.
     *
     * @return \App\Controller\Admin\AdminOrderController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\Admin\\AdminOrderController'] = $instance = new \App\Controller\Admin\AdminOrderController(($container->privates['App\\Repository\\OrderRepository'] ?? $container->load('getOrderRepositoryService')), ($container->services['doctrine.orm.default_entity_manager'] ?? $container->load('getDoctrine_Orm_DefaultEntityManagerService')), ($container->privates['App\\Twig\\Runtime\\OrderDateFormatRuntime'] ??= new \App\Twig\Runtime\OrderDateFormatRuntime()), ($container->privates['App\\Twig\\Runtime\\LocationExtensionRuntime'] ??= new \App\Twig\Runtime\LocationExtensionRuntime()), new \App\Services\DistanceCalculator(($container->privates['App\\Repository\\UserRepository'] ?? $container->load('getUserRepositoryService'))));

        $instance->setContainer(($container->privates['.service_locator.CshazM0'] ?? $container->load('get_ServiceLocator_CshazM0Service'))->withContext('App\\Controller\\Admin\\AdminOrderController', $container));

        return $instance;
    }
}
