<?php

namespace ContainerX3A4xm2;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCurrentPasswordValidatorService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Validator\CurrentPasswordValidator' shared autowired service.
     *
     * @return \App\Validator\CurrentPasswordValidator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Validator\\CurrentPasswordValidator'] = new \App\Validator\CurrentPasswordValidator(($container->privates['security.user_password_hasher'] ?? $container->load('getSecurity_UserPasswordHasherService')), ($container->privates['security.helper'] ?? $container->load('getSecurity_HelperService')));
    }
}
