<?php

namespace ContainerX3A4xm2;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCakesControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\CakesController' shared autowired service.
     *
     * @return \App\Controller\CakesController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\CakesController'] = $instance = new \App\Controller\CakesController(($container->privates['App\\Repository\\CakeRepository'] ?? $container->load('getCakeRepositoryService')), ($container->privates['App\\Services\\VisitCounter'] ?? $container->load('getVisitCounterService')), ($container->services['doctrine.orm.default_entity_manager'] ?? $container->load('getDoctrine_Orm_DefaultEntityManagerService')), new \App\Converter\CakeConverter(($container->privates['App\\Twig\\Runtime\\PicturePathExtensionRuntime'] ?? $container->load('getPicturePathExtensionRuntimeService'))));

        $instance->setContainer(($container->privates['.service_locator.CshazM0'] ?? $container->load('get_ServiceLocator_CshazM0Service'))->withContext('App\\Controller\\CakesController', $container));

        return $instance;
    }
}
