<?php

namespace ContainerX3A4xm2;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCakeRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\CakeRepository' shared autowired service.
     *
     * @return \App\Repository\CakeRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->services['knp_paginator'] ?? $container->load('getKnpPaginatorService'));

        if (isset($container->privates['App\\Repository\\CakeRepository'])) {
            return $container->privates['App\\Repository\\CakeRepository'];
        }

        return $container->privates['App\\Repository\\CakeRepository'] = new \App\Repository\CakeRepository(($container->services['doctrine'] ?? $container->getDoctrineService()), $a);
    }
}
