<?php

namespace ContainerX3A4xm2;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCarouselItemPaddingCalculatorRuntimeService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Twig\Runtime\CarouselItemPaddingCalculatorRuntime' shared autowired service.
     *
     * @return \App\Twig\Runtime\CarouselItemPaddingCalculatorRuntime
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Twig\\Runtime\\CarouselItemPaddingCalculatorRuntime'] = new \App\Twig\Runtime\CarouselItemPaddingCalculatorRuntime();
    }
}
