<?php

namespace ContainerX3A4xm2;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEmailExistValidatorService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Validator\EmailExistValidator' shared autowired service.
     *
     * @return \App\Validator\EmailExistValidator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Validator\\EmailExistValidator'] = new \App\Validator\EmailExistValidator(($container->privates['App\\Repository\\UserRepository'] ?? $container->load('getUserRepositoryService')));
    }
}
