<?php

namespace ContainerX3A4xm2;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLogoutSubscriberService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\EventSubscriber\LogoutSubscriber' shared autowired service.
     *
     * @return \App\EventSubscriber\LogoutSubscriber
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\EventSubscriber\\LogoutSubscriber'] = new \App\EventSubscriber\LogoutSubscriber(($container->services['request_stack'] ??= new \Symfony\Component\HttpFoundation\RequestStack()));
    }
}
