<?php

namespace ContainerX3A4xm2;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPasswordCreateTypeService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Form\PasswordCreateType' shared autowired service.
     *
     * @return \App\Form\PasswordCreateType
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Form\\PasswordCreateType'] = new \App\Form\PasswordCreateType();
    }
}
