<?php

namespace ContainerX3A4xm2;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getVisitSearchFilterTypeService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Form\VisitSearchFilterType' shared autowired service.
     *
     * @return \App\Form\VisitSearchFilterType
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Form\\VisitSearchFilterType'] = new \App\Form\VisitSearchFilterType();
    }
}
